### ISSUE TITLE
TrainerDex Branding Spec

### ISSUE THREAD

**Issue by JayTurnr** [TrainerDex/TrainerDex.py#23]
## Name

TrainerDex is comprised of two parts: Trainer and Dex. There shouldn't be a space between the two but they should be indicated by a change in capitalisation or font size.

#### Use
- [x] TrainerDex
- [x] TRAINERDEX - although discouraged
- [x] TDX
#### Don't use
- [ ] Trainerdex
- [ ] trainerdex
- [ ] Tdx
- [ ] TDx
- [ ] tdx

### RED

HEX: #ca3755
RGB: 202 55 85

### BLACK

HEX: #332e20
RGB: 51 46 32

### WHITE

HEX: #f2f2f2
RGB: 242 242 242

## Font

* [Raleway (Extra Bold & Light)](https://fonts.google.com/specimen/Raleway)

**Comment by TurnrDev** [comment]
Converted to [wiki](https://github.com/TrainerDex/TrainerDex.py/wiki/TrainerDex-Branding-Spec)
