### ISSUE TITLE
Rename required!

### ISSUE THREAD

**Issue by JayTurnr** [TrainerDex/TrainerDex.py#4]
As part of the overall project, I'm building a website. The API will be hosted there rather than backing off another domain I have. Unfortunately, trainerdex.com is taken, and EXPENSIVE.
So here goes: Rebranding is needed.
 I'm going to need to pick a new brand.

Considered:
* ~~[Pokemon Trainer World](http://pokemontrainer.world.com/)~~ - **Rejected** - Facebook username is already taken.
* ~~[Pokemon Trainer Network](http://pokemontrainer.network.com/)~~ - **Rejected** - Too similar to [Pokemon Trainer Club](https://www.pokemon.com/uk/pokemon-trainer-club), risk of C&D too high, won't ever make it to first page on Google.
* [TrainerDex.co.uk](http://trainerdex.co.uk/) - **Considering** - Implies service is regional to the UK.

- [x] Buy domain
- ~~Rename PyPi packages~~
- [x] Add new URL to library

**Comment by TurnrDev** [comment]
Bought TrainerDex.co.uk
